# Generated by Django 3.2.7 on 2021-09-02 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogger_name', models.CharField(max_length=100, verbose_name='name')),
                ('bio', models.TextField(help_text='Enter the biography about the blogger', max_length=500)),
            ],
            options={
                'ordering': ['blogger_name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Enter the content of a post', max_length=1000)),
                ('date_of_post', models.DateField(blank=True, null=True)),
                ('blogger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogger')),
            ],
            options={
                'ordering': ['date_of_post'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Enter the comment of a post', max_length=1000)),
                ('date_of_comment', models.DateField(blank=True, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='blog.post')),
            ],
            options={
                'ordering': ['date_of_comment'],
            },
        ),
    ]
