# Generated by Django 3.2.7 on 2021-09-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name_commented',
            field=models.CharField(default=2, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
