# Generated by Django 3.2.7 on 2021-09-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_user_name_commented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_name_commented',
        ),
    ]
