# Generated by Django 3.2.7 on 2021-09-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_of_post'], 'permissions': (('can_view_blogs', 'View blogs as blogger'),)},
        ),
    ]
